from .add import Add
from .sub import Sub
from .xor import Xor
from .and_ import And
from .or_ import Or
from .addi import Addi
from .xori import Xori
from .ori import Ori
from .andi import Andi
from .beq import Beq
from .bne import Bne
from .lw import LW
from .sw import SW
from .halt import HALT
